### ISSUE TITLE
regional-sts branch ssl issue

### ISSUE THREAD

**Issue by srb3** [Kong/lua-resty-aws#17] opened 2022-05-26 14:42 UTC
I was digging a bit deeper into this issue and I wanted to share what I had found:
https://github.com/Kong/lua-resty-aws/blob/regional-sts/src/resty/aws/request/execute.lua#L25

verified I was getting the same error with ssl and lua-resty-aws and lua-resty-secrets:

```
AWS_REGION=eu-west-1 KONG_PASSWORD=password /usr/local/bin/kong migrations bootstrap -c /etc/kong/kong.conf  --vv
....
....
....
2022/05/26 14:33:35 [debug] lua_ssl_trusted_certificate = {"/etc/pki/tls/certs/ca-bundle.crt"}
....
....
....
2022/05/26 14:33:35 [verbose] generating trusted certs combined file in
2022/05/26 14:33:36 [warn] [Penlight 1.12.0] the contents of module 'pl.xml' has been deprecated, please use a more specialized library instead (deprecated after 1.11.0, scheduled for removal in 2.0.0)
2022/05/26 14:33:36 [error] 21988#0: *2 [lua] init.lua:285: update(): [Secrets aws-sm] failed to fetch secrets: failed to retrieve secret 'arn:aws:secretsmanager:eu-west-1:412431539555:secret:postgres_credentials_secret-fun20r-S0MVRL' (stage 'AWSCURRENT'): SecretsManager:getSecretValue() failed to connect to 'https://secretsmanager.eu-west-1.amazonaws.com:443': 20: unable to get local issuer certificate, context: ngx.timer
Error:
/usr/local/share/lua/5.1/kong/cmd/migrations.lua:227: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: ["failed to retrieve secret 'arn:aws:secretsmanager:eu-west-1:412431539555:secret:postgres_credentials_secret-fun20r-S0MVRL' (stage 'AWSCURRENT'): SecretsManager:getSecretValue() failed to connect to 'https:\/\/secretsmanager.eu-west-1.amazonaws.com:443': 20: unable to get local issuer certificate"]
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/cmd/migrations.lua:227: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:97: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:97>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:97: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:54>
        /usr/local/bin/kong:9: in function 'file_gen'
        init_worker_by_lua:50: in function <init_worker_by_lua:48>
        [C]: in function 'xpcall'
        init_worker_by_lua:57: in function <init_worker_by_lua:55>
```

I then confirmed that all the system certificates in on my test servers / containers could be used to call the `https://secretsmanager.eu-west-1.amazonaws.com` endpoint without causing an ssl error

```
curl --cacert /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem -i https://secretsmanager.eu-west-1.amazonaws.com
HTTP/1.1 404 Not Found
x-amzn-RequestId: b31461a4-9bb9-4ba1-8eb5-ad98ebb8fa46
Content-Length: 29
Date: Thu, 26 May 2022 09:03:49 GMT

<UnknownOperationException/>
```

I then fixed the control plane by hard coding the database password and username in the kong.conf, now it bootstrapped fine

and I could log in, this was interesting as by logging in I was using the more secret references stored in aws secrets manager for the oidc plugin

```
admin_gui_auth_conf      = {"verify_parameters":false,"auth_methods":["authorization_code","password"],"authenticated_groups_claim":["roles"],"client_id":["ext:{\"type\":\"aws-sm\",\"key\":\"client_id\",\"config\":{\"SecretId\":\"arn:aws:secretsmanager:***************\"}}"],"client_secret":["ext:{\"type\":\"aws-sm\",\"key\":\"client_secret\",\"config\":{\"SecretId\":\"arn:aws:secretsmanager:********************************\"}}"],"consumer_by":["username"],"admin_claim":"name","issuer":"https://login.microsoftonline.com/43fa6b04-e14c-4e06-be5b-758ec24308d5/v2.0/.well-known/openid-configuration","login_redirect_uri":["https://kong-steveb-wpb-aws-fun20r.kong-cx.com/"],"logout_methods":["GET","DELETE","POST"],"logout_query_arg":"logout","logout_redirect_uri":["https://kong-steveb-wpb-aws-fun20r.kong-cx.com/"],"redirect_uri":["https://kong-steveb-wpb-aws-fun20r.kong-cx.com/"],"scopes":["openid","profile","email","ext:{\"type\":\"aws-sm\",\"key\":\"scopes\",\"config\":{\"SecretId\":\"arn:aws:secretsmanager:*********************************************\"}}"],"ssl_verify":false,"http_proxy":"http://ip-10-99-0-236.eu-west-1.compute.internal:3128","https_proxy":"http://ip-10-99-0-236.eu-west-1.compute.internal:3128"}

```

this means that after the bootstrap there are no ssl issues when retrieving other control plane secrets.

I also then tested the data planes, these use the aws secrets manager for splunk tokens - the data planes all work without issue.

The only time this SSL issue occurs is during the bootstrap of Kong.

hopefully this helps somewhat in trying to get to the bottom of the issue.

**Comment by Tieske** [comment] 2022-05-31 21:19
for reference root cause discussed here: https://github.com/Kong/lua-resty-aws/pull/14#discussion_r857102984

closing this.

**Closed by Tieske** 2022-05-31 21:19 UTC
